### ISSUE TITLE
Getting error TypeError: startingRef.get is not a function

### ISSUE THREAD

**Issue by tusharmm** [jloosli/node-firestore-import-export#1]
>firestore-export --accountCredentials ..\sales-buddy-v2-firebase-adminsdk-6euxz-526882fedf.json --backupFile myDatabase1.json --prettyPrint
TypeError: startingRef.get is not a function

I'm a newbie, so might be missing something basic. Please help

**Comment by jloosli** [comment]
Did the export still happen, but you got a warning, or did it no happen at all? The root of a Firestore database is kind of like a document, so I kind of treat it like one...I'll test it out and get back to you.

**Comment by jloosli** [comment]
I've got some issues with deploying this to NPM...I'll have that fixed hopefully this afternoon.

**Comment by tusharmm** [comment]
No, the export didn't happen at all. Await the fix.
