### ISSUE TITLE
firestore-export: The term 'firestore-export' is not recognized as a cmdlet name,

### ISSUE THREAD

**Issue by leticiafatima** [jloosli/node-firestore-import-export#168]
### Expected behavior
the code execute

### Actual behavior
error appears: firestore-export: The term 'firestore-export' is not recognized as a cmdlet name, and does not execute

### Steps to reproduce the behavior
firestore-export --accountCredentials path/credentials.json --backupFile /backups/myDatabase.json

**Comment by jloosli** [comment]
After installing the package, the command line tools are installed in the npm/yarn bin directory. Try the following:
`$(npm bin)firestore-export --accountCredentials path/credentials.json --backupFile /backups/myDatabase.json`
