### ISSUE TITLE
firestore-import throws TypeError exception

### ISSUE THREAD

**Issue by BenSchZA** [jloosli/node-firestore-import-export#21]
### Expected behavior
firestore-import should upload the backup file to Firestore

### Actual behavior
firestore-import throws a TypeError exception:

`TypeError: Cannot read property 'projectId' of undefined
TypeError: Cannot read property 'projectId' of undefined
    at /home/bscholtz/.nvm/versions/node/v9.1.0/lib/node_modules/node-firestore-import-export/dist/bin/firestore-import.js:71:33
    at <anonymous>`

### Steps to reproduce the behavior

Running firestore-export works, this indicates the credentials are set up correctly. When running firestore-import, the exception above is thrown.

**Comment by BenSchZA** [comment]
By hard-coding the projectID as follows it works as expected:

File: **firestore-import.js:71:33**
`// For some reason, Firestore, DocumentReference, and CollectionReference interfaces
 // don't show a projectId property even though they do have them.
// @todo: Remove any when that is fixed, or find the correct interface
var projectID = 'my-project-id';`

**Comment by jloosli** [comment]
I know there were some issues with the export from Firebase handling the capitalization differently than the typescript interface. I thought that I had gotten around that by casting that as an "any". I'm hoping when I refactor this with the latest Firebase libraries that this will get resolved.

**Comment by BenSchZA** [comment]
Thanks for the feedback @jloosli. Let me know if there's anything I can do to help.
