### ISSUE TITLE
firestore-clear wait for 5 seconds

### ISSUE THREAD

**Issue by benzsuankularb** [jloosli/node-firestore-import-export#275]
### Expected behavior
I expected `firestore-clear -a xxx.json -y` not to wait for 5 seconds.
I think this is too opinionated, or at lease have an option for this.
I just want to flush all and setUp the next test case. :)

### Actual behavior
It's waiting for 5 seconds before operation start.

**Comment by jloosli** [comment]
That's a good point...I'll rethink that

**Comment by jloosli** [comment]
I added another command line option to remove the 5 second delay in version 1.0.1
