### ISSUE TITLE
Not working correctly in Firebase Functions

### ISSUE THREAD

**Issue by Autospace** [jloosli/node-firestore-import-export#31]
### Expected behavior
Firestore Database backup .json file should be as is if we use console commands.
### Actual behavior
Backup .json file contains wrong data. No __datatype__ entities inside.
### Steps to reproduce the behavior
Inside Firebase Functions:

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const db = admin.firestore()
const firestoreImportExport = require('node-firestore-import-export')

exports.createFirestoreBackup = functions.https.onRequest((request, response) => {
      firestoreImportExport.firestoreExport(db).then(data => {
               // data is wrong
      })
})

**Comment by jloosli** [comment]
@Autospace I'm not sure if you're still using this or not, but I've just released a refactoring of this and I'm wondering if it fixes your issues. Let me know if you still see problems.

**Comment by jloosli** [comment]
Closing for now since I can't replicate.
