### ISSUE TITLE
Error on running import command

### ISSUE THREAD

**Issue by morariu** [jloosli/node-firestore-import-export#314]
### Expected behavior
Importing data from the .json file to the firestore database.

### Actual behavior
Getting the error while running the correct command as per documentation.

`error: unknown option `--backupFile userSettings.json'`

### Steps to reproduce the behavior
Running the command:

firestore-import --accountCredentials serviceAccountKey.json --backupFile userSettings.json --nodePath userSettings

**Comment by jloosli** [comment]
Hmm...I can't replicate that issue. If you have more information, please add it. Thanks.
