### ISSUE TITLE
Error: Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field user.userRef).

### ISSUE THREAD

**Issue by pollo17385** [jloosli/node-firestore-import-export#36]
### Expected behavior
Make an normal import of the TimeStamp type.

### Actual behavior
When trying to import a export made on 0.10.4 I get this error:

Error: Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field user.userRef).
Error: Argument "data" is not a valid Document. Cannot use "undefined" as a Firestore value (found in field user.userRef).
    at Validator.(anonymous function).values [as isDocument] (C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\node_modules\firebase-admin\node_modules\@google-cloud\firestore\build\src\validate.js:92:27)
    at WriteBatch.set (C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\node_modules\firebase-admin\node_modules\@google-cloud\firestore\build\src\write-batch.js:225:25)
    at C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\lib\import.js:66:19
    at Array.map (<anonymous>)
    at C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\lib\import.js:55:22
    at Array.map (<anonymous>)
    at setDocuments (C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\lib\import.js:53:32)
    at Object.importData [as default] (C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\lib\import.js:27:43)
    at C:\Users\Pc\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\bin\firestore-import.js:96:28
    at <anonymous>

PD: The field userRef that is mentioned in the error is of type reference, like this "userRef: users/oRVksmPWOsXPJNFrmbGP359t6J03"

### Steps to reproduce the behavior
Make an export of the DB and then try to import it.

**Comment by pollo17385** [comment]
this is the part of the JSON that is referenced in the error:

"1XgUbUDfwue3FMpZLuqy": {
        "service": 5,
        **"user": {
          "userRef": {
            "__datatype__": "documentReference",
            "value": "users/WQuGJoMVf6d9HffF04g53G0mWif2"
          },**
          "displayName": "Noel Farías"
        },
        "food": 5,
        "speed": 5,
        "__collections__": {}
      },

@jloosli

**Comment by A1iAshoor** [comment]
+1

**Comment by pollo17385** [comment]
@jloosli I still have the exact same error of this issue on version 0.12.0

**Comment by jloosli** [comment]
@pollo17385 Looking closer at https://github.com/jloosli/node-firestore-import-export/issues/36#issuecomment-441460805 it shows 

```
"userRef": {
"datatype": "documentReference",
"value": "users/WQuGJoMVf6d9HffF04g53G0mWif2"
}
```

but datatype should have exported as __datatype__, like below:

```
"userRef": {
"__datatype__": "documentReference",
"value": "users/WQuGJoMVf6d9HffF04g53G0mWif2"
}
```

Is that just a copy/paste issue, or did the export not format it correctly?

**Comment by jloosli** [comment]
@pollo17385 I'm so dumb...I published this without building it first. Update to the latest and try it and let me know if it works for you.

**Comment by pollo17385** [comment]
Jared, this things happen.
Now its working flawlessly. Thanks for your work and your time!!

Greetings Gonzalo.

**Comment by jloosli** [comment]
Glad to hear it's working!
