### ISSUE TITLE
Clear database

### ISSUE THREAD

**Issue by Endran** [jloosli/node-firestore-import-export#38]
### Feature request

For my test setup I would like to be able to clear the entire db before importing. Something like:
`firestore-clear -a firebase-admin.json -y`.

Is this something you would considering added, or merge in if I would have a PR?

**Comment by jloosli** [comment]
I'm looking into this...I'll probably have an initial run put together by the end of the week.

**Comment by jloosli** [comment]
@Endran I've implemented this, but haven't got it fully tested out yet. Feel free to checkout the pull request, try it out, and give me any feedback you might have.
