### ISSUE TITLE
"Export full database" doesn't export sub-collections of empty collections

### ISSUE THREAD

**Issue by RaMMicHaeL** [jloosli/node-firestore-import-export#42]
Look at the screenshot below for an example. I have a user, id `0DLt5O1ma0d...`, whose document doesn't exist, but there is a sub-collection with documents. When doing full database export (`firestore-export --accountCredentials path/to/credentials/file.json --backupFile /backups/myDatabase.json`), the sub-collection of this user is not exported.

![image](https://user-images.githubusercontent.com/4129781/51033332-bf9f7480-15ab-11e9-8369-49b951b99907.png)

**Comment by jloosli** [comment]
Unfortunately, this is an issue outside of this tool's control. From the [Firestore documentation](https://firebase.google.com/docs/firestore/manage-data/delete-data) (note the part I put in bold):

> When you delete a document, Cloud Firestore does not automatically delete the documents within its subcollections. You can still access the subcollection documents by reference. For example, you can access the document at path /mycoll/mydoc/mysubcoll/mysubdoc even if you delete the ancestor document at /mycoll/mydoc.

> **Non-existent ancestor documents appear in the console, but they do not appear in query results and snapshots**.

> If you want to delete a document and all the documents within its subcollections, you must do so manually. For more information, see Delete Collections.

When you delete a document in the console, Firebase automatically goes down the tree to remove all the subcollections as well, but if you're removing documents programatically, you need to take care of that yourself. I'm working on a tool that will do the recursive deletion of data (see #38), but as for taking care of the already orphaned data, you'll probably need to figure out some other way to address that.
