### ISSUE TITLE
firestore-clear CLI is not working

### ISSUE THREAD

**Issue by amerbazerbachi** [jloosli/node-firestore-import-export#43]
### Expected behavior
To delete my entire DB information

### Actual behavior
Error:
'firestore-clear' is not recognized as an internal or external command, operable program or batch file.

### Steps to reproduce the behavior
Just execute the command.
firestore-import works perfectly
firestore-export works perfectly.

**Comment by jloosli** [comment]
@amerbazerbachi Thanks for catching this
