### ISSUE TITLE
Special characters bug on export

### ISSUE THREAD

**Issue by andreescocard** [jloosli/node-firestore-import-export#48]
### Expected behavior
Export displaying the special character, examples:  café,pedaço, açúcar

### Actual behavior
Exporting like this:  caf├®,l peda├ºo, a├º├║car

### Steps to reproduce the behavior
Export using library with special character

**Comment by jloosli** [comment]
Can you send me an example of the exported file? This seems like it's a web browser not using utf8 characters.

**Comment by andreescocard** [comment]
'0dIOU1NABRsQvCRJLeX6':
   { uid: '',
     endereco: '',
     habitos:
      { data: [Object],
        atividade:
         'pedal as vezes, futebol, por├®m esta tendo as ocila├º├Áes de press├úo  e come├ºou a academia a uma semana ',
        cigarro: 'n├úo',
        tipoBebida: '',
        bebida: 'n├úo',
        medicamentos: 'anticoncepcional ' },
     nascimento: '28/12/1993',
     celular: 'xxxxxxxxxx',
     email: '',
     recordatorio:
      { lancheTarde:
         'doce, bolo de pote, a├ºa├¡ ou milk shake s├│ porcarias at├® ir para casa ',
        jantar: 'janta ou lanche com refrigerante ',
        lanhe: '',
        ceia: 'doce/ finais de semana ├® s├│ porcaria ',
        almoco:
         '11:30 batata frita, arroz , feij├úo, n├úo gosta muito de verduras, carne, refrigerante ou suco de pacotinho, doce',
        cafe:
         'leite com caf├® e p├úo com manteiga ou p├úo de queijo 08:00/08:30' },
     motivo:
      'esta acima do peso e esta tendo altera├º├úo de press├úo e muito incha├ºo nas pernas, teve uma bebe em 2012 e emagreceu porem de 2 anos pra c├í que come├ºou a engordar mais ',
     nome: 'xxxxxxxxxx',
     cidade: '',
     __collections__: { anamnese: [Object], dieta: [Object] } },

**Comment by jloosli** [comment]
I'm thinking this might be a terminal issue...do you have the same problems when exporting to a file using the command line?

**Comment by andreescocard** [comment]
Yes, i am exporting the console.log to file
Using node .\script.js >> filename.txt

**Comment by andreescocard** [comment]
Your repo is the only one that works for me using library > exporting
The command to export full database create folder with collection names empty

**Comment by jloosli** [comment]
Can't replicate
