### ISSUE TITLE
Subcollections displayed as [Object]

### ISSUE THREAD

**Issue by andreescocard** [jloosli/node-firestore-import-export#49]
### Expected behavior
Show subcollection data

### Actual behavior
Exporting like:

uid:
   { email: '',
     __collections__:
      { one: [Object],
        two: [Object],
        three: [Object],
        four: [Object] } },

### Steps to reproduce the behavior
Export using library with subcollections

**Comment by jloosli** [comment]
This seems like you're trying to display the entire object in a web browser. I'm guessing you would need to wrap the result in JSON.serialize() before echoing it to the browser window.

**Comment by andreescocard** [comment]
I am using the console.log example in docs, running with node

**Comment by jloosli** [comment]
Ahhh...that makes sense. I'll have to fix the example to be something like the following:

```
firestoreExport(collectionRef)
    .then(data=>console.log(JSON.stringify(data)));
```

**Comment by andreescocard** [comment]
Thanks! Now it's working here
