### ISSUE TITLE
Random Document ID please

### ISSUE THREAD

**Issue by ghost** [jloosli/node-firestore-import-export#494]
Hello;
i truly love this but i need some help, i did a sample import but the issue is that all the things i imported went from `0,1,3,4,5,6,7,8,9,10,11..` is there anyway to get random document id?

**Comment by Prajwal-Koirala** [comment]
Update: I made a script in golang for this.
```https://gist.github.com/Prajwal-Koirala/765c1735a65426ef6b72a163429d1f03```

**Comment by ghost** [comment]
Just going to rewrite this in golang cause of the amount of errors.
```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (20954288616) is greater than possible Buffer: 2147483647 bytes
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (20954288616) is greater than possible Buffer: 2147483647 bytes
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:264:11)
```
