### ISSUE TITLE
Error: function crashed out of request scope Function invocation was interrupted.

### ISSUE THREAD

**Issue by jay8t6** [jloosli/node-firestore-import-export#50]
Is there a limit on how many documents it can retrieve? I am getting this error in the middle of retrieving documents:

`Error: function crashed out of request scope Function invocation was interrupted.`

**Comment by jay8t6** [comment]
closing. It was a problem with my cloud function, I just had to return the promise.

**Comment by jay8t6** [comment]
@jloosli this problem is back. Do you have any idea what's going on? it crashes in the middle of retrieving users data.

**Comment by jloosli** [comment]
Not really....I know that the API has some rate limiting on it, so when the code hits some rate limit errors, it tries to wait before getting more items, but maybe there are other places where I should place the waiting code.

**Comment by jay8t6** [comment]
@jloosli I think there are places in the code that needs to return promises, because it consistently crashes in the middle of retrieving the documents. Would you able to check on this issue please? I'd really appreciate it!
