### ISSUE TITLE
implementation on browser + ionic 

### ISSUE THREAD

**Issue by joel1725** [jloosli/node-firestore-import-export#51]
### Expected 

Hi!

I would like to be able to use this library in my ionic project, but I do not know how to configure it.

You could help me get more explicitly about where to place an index.html, with a js .. file so I can use the library.

I downloaded the github example, I have my firestore file but I do not know how to put any code in it.

I am sorry that this comment is very novice, but I have tried many things and I can not find the way

**Comment by jloosli** [comment]
The Admin API is only available on the server side of things, so I don't think you'd be able to use this within the browser or Ionic. I would recommend trying it on the back end.
