### ISSUE TITLE
Memory issues when trying to export large datasets

### ISSUE THREAD

**Issue by Endran** [jloosli/node-firestore-import-export#74]
We use `node-firestore-import-export` on a daily basis for im/export of several test Firestore instances. Next to that we use it as a secondary backup path for production. Or production database is growing quite large, and we run into memory issues when resolving 20.000+ promises simultaneously.

### Expected behavior
A successful export via Cloud Function

### Actual behavior

```
Error: memory limit exceeded. Function invocation was interrupted.
Error: function crashed out of request scope Function invocation was interrupted.
```

### Steps to reproduce the behavior
Create a DB with several collections with far over 20.000 documents, and try to run an export via a Cloud Function.

**Comment by amstrad** [comment]
Having similar issue. 
I run a cron job backup triggering a firebase function, we get all data to memory first and write it to firestorage. This functions works on another project with a smaller amount of data..not not on produciton 
I also increased the functions timeout and memory to max in glcoud, but it´s seems not enough

```
const collectionRef = firebase.firestore()  
let data = await firestoreExport(collectionRef);
```

 "Error: function crashed out of request scope Function invocation was interrupted."

Would appreciate any idea fix before switchign to the official [glcoud method](https://firebase.google.com/docs/firestore/solutions/schedule-export)

**Comment by Endran** [comment]
It's a difficult one to fix in this form, since you need al data in mem to build the JSON tree. See the PR for some more details @amstrad 
https://github.com/jloosli/node-firestore-import-export/pull/75#issuecomment-511388018

**Comment by amstrad** [comment]
Thanks Edran. Streaming directly to file would be great. Checked your package, but seems "Import is not functionally yet."?, i´ll keep an eye on it, while moving my backups to the official gcloud method. Thanks
