### ISSUE TITLE
JSON data not being imported into Firebase Emulator

### ISSUE THREAD

**Issue by ThatZacman** [jloosli/node-firestore-import-export#845]
When I import the data using the `firestore-import --accountCredentials serviceAccountFile.json --backupFile output.json` command the process runs successfully, but when refreshing the emulator there is no data in Firestore.  What could I be doing wrong as the exported json file hasn't been altered.

The commands that I run were:

- `firestore-export --accountCredentials serviceAccountFile.json --backupFile output.json`
- `export FIRESTORE_EMULATOR_HOST=0.0.0.0:8081` (I have confirmed the port is correct as it throws an error when attempting another port).
- `firestore-import --accountCredentials serviceAccountFile.json --backupFile output.json`

Is it still possible to import data this way?  Any help would be greatly appreciated.

Thanks in advance.

**Comment by ThatZacman** [comment]
The issue was that the service account credentials I had generated from firebase was not for the same project I had linked my firebase emulator too.

**Comment by pascalbe-dev** [comment]
Hey, I'm having a similar issue. 

I actually do get a "All done 🎉" result, but no data is imported to the emulator. I'm also wondering, if the account credentials are required and if yes, which ones I should use. 

Does anyone have a tipp?
